// This file is a placeholder for development
// The actual generated types are created in dist/runtime/components.generated.d.ts during build
// Run 'yarn run prepack' to generate the full type definitions
/* eslint-disable */

export interface AutoGeneratedGlobalComponents {
  // Component types will be generated during build
}
