#!/usr/bin/env node
import { readdir, writeFile } from 'node:fs/promises'
import { join, relative, parse } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const componentsDir = join(__dirname, '../src/runtime/components')
const outputFile = join(__dirname, '../src/runtime/components.d.ts')

// Convert filename to PascalCase component name with prefix
function toPascalCase (str: string): string {
  return str
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}

function getComponentName (filePath: string, prefix: string, includePathPrefix: boolean): string {
  const parsed = parse(filePath)
  const dir = parsed.dir
  const name = parsed.name

  // Remove .client or .server suffix
  const cleanName = name.replace(/\.(client|server)$/, '')

  // Build the component name
  let componentName = prefix

  if (includePathPrefix && dir) {
    // Add directory path as part of the name (e.g., admin/user-form -> TlAdminUserForm)
    const dirParts = dir.split('/').filter(Boolean)
    componentName += dirParts.map(toPascalCase).join('')
  }

  componentName += toPascalCase(cleanName)

  return componentName
}

async function* walk (dir: string, basePath: string = ''): AsyncGenerator<string> {
  const entries = await readdir(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = join(dir, entry.name)
    const relativePath = basePath ? join(basePath, entry.name) : entry.name

    if (entry.isDirectory()) {
      yield* walk(fullPath, relativePath)
    } else if (entry.isFile() && entry.name.endsWith('.vue')) {
      yield relativePath
    }
  }
}

async function generateComponentTypes () {
  const components: string[] = []

  // Collect all .vue files
  for await (const filePath of walk(componentsDir)) {
    components.push(filePath)
  }

  // Sort for consistent output
  components.sort()

  // Generate type declarations
  const prefix = 'Tl'
  const includePathPrefix = true // Set to match your addComponentsDir config

  const typeDeclarations = components.map((filePath) => {
    const componentName = getComponentName(filePath, prefix, includePathPrefix)
    const importPath = `./components/${filePath.replace(/\\/g, '/')}`
    return `    ${componentName}: typeof import('${importPath}')['default']`
  }).join('\n')

  const output = `// Auto-generated by scripts/generate-component-types.ts
// Do not edit this file manually

// Declare global component types for strict template type checking
declare module 'vue' {
  export interface GlobalComponents {
${typeDeclarations}
  }
}

export {}
`

  await writeFile(outputFile, output, 'utf-8')
  console.log(`✅ Generated component types for ${components.length} components`)
  console.log(`📝 Output: ${relative(process.cwd(), outputFile)}`)
}

generateComponentTypes().catch(console.error)
