#!/usr/bin/env node
import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, extname } from 'node:path'

const COMPONENTS_DIR = 'src/runtime/components'
const OUTPUT_FILE = 'dist/runtime/components.generated.d.ts'
const COMPONENT_PREFIX = 'Tl'

// Convert filename to PascalCase component name with prefix
function fileToComponentName (relativePath: string): string {
  // Remove .vue extension
  let withoutExt = relativePath.replace(/\.vue$/, '')

  // Remove special Nuxt suffixes (.client, .server, etc.)
  withoutExt = withoutExt.replace(/\.(client|server)$/, '')

  // Split by slashes and dashes, convert to PascalCase
  const parts = withoutExt.split(/[/-]/)
  const pascalCase = parts
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')

  return COMPONENT_PREFIX + pascalCase
}

// Recursively scan directory for component files
function scanComponents (dir: string, baseDir: string = dir): string[] {
  const components: string[] = []

  const entries = readdirSync(dir)

  for (const entry of entries) {
    const fullPath = join(dir, entry)
    const stat = statSync(fullPath)

    if (stat.isDirectory()) {
      // Recursively scan subdirectories
      components.push(...scanComponents(fullPath, baseDir))
    } else if (stat.isFile()) {
      const ext = extname(entry)
      // Include .vue files only
      if (ext === '.vue'
        && !entry.includes('.test.')
        && !entry.includes('.spec.')) {
        const relativePath = relative(baseDir, fullPath)
        components.push(relativePath)
      }
    }
  }

  return components
}

// Scan for components
const componentFiles = scanComponents(COMPONENTS_DIR)

// Sort for consistent output
componentFiles.sort()

// Generate type declarations
const declarations = componentFiles.map((filePath) => {
  const componentName = fileToComponentName(filePath)
  const importPath = `../../${COMPONENTS_DIR}/${filePath}`
  return `    ${componentName}: typeof import('${importPath}')['default']`
}).join('\n')

// Generate lazy component declarations
const lazyDeclarations = componentFiles.map((filePath) => {
  const componentName = fileToComponentName(filePath)
  const importPath = `../../${COMPONENTS_DIR}/${filePath}`
  return `    Lazy${componentName}: LazyComponent<typeof import('${importPath}')['default']>`
}).join('\n')

// Generate the complete file content
const generatedContent = `// This file is auto-generated by scripts/sync-component-types.ts
// DO NOT EDIT MANUALLY - Run 'yarn run prepack' to update
/* eslint-disable */

export interface AutoGeneratedGlobalComponents {
${declarations}
${lazyDeclarations}
  }
`

// Write the generated file
writeFileSync(OUTPUT_FILE, generatedContent)

console.log(`✓ Generated ${componentFiles.length} component types to ${OUTPUT_FILE}`)
